import os
Import('env')
local_env = env.Clone()

root = os.path.dirname(Dir('.').srcnode().abspath)

# Build Division Problems
local_env.Mako(
    'longdivision.tex', 'longdivision.tex.mako',
    MAKO_DICTIONARY={'SEED': 43})

pdf = local_env.PDF('document.tex')
install = local_env.InstallAs('Homework.pdf', pdf)
Return('install')
